micronaut:
  application:
    name: deffunCloud
  router:
    static-resources:
      default:
        enabled: true
        mapping: "/**"
        paths:
          - "classpath:public"
  server:
    cors:
      enabled: true
  security:
    authentication: idtoken
    oauth2:
      clients:
        google:
          client-id: '${GOOGLE_OAUTH_CLIENT_ID}'
          client-secret: '${GOOGLE_OAUTH_CLIENT_SECRET}'
          openid:
            issuer: 'https://accounts.google.com'
    redirect:
      unauthorized:
        url: "/login"
    intercept-url-map:
      - pattern: "/**"
        httpMethod: GET
        access:
          - isAnonymous()
    endpoints:
      logout:
        get-allowed: true
#datasources:
#  default:
#    driverClassName: org.mariadb.jdbc.Driver
#    db-type: mariadb
#    dialect: MYSQL
datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    entity-scan:
      packages: io.deffun
    properties:
      hibernate:
        hbm2ddl:
          auto: create-drop
graphql:
  graphiql:
    enabled: true
netty:
  default:
    allocator:
      max-order: 3
#deffun-cloud:
#  ssh:
