micronaut:
  application:
    name: deffunCloud
datasources:
  default:
    driverClassName: org.mariadb.jdbc.Driver
    db-type: mariadb
    dialect: MYSQL
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
netty:
  default:
    allocator:
      max-order: 3
