
ALTER TABLE projects ADD COLUMN IF NOT EXISTS test BOOL DEFAULT false;
ALTER TABLE projects ADD COLUMN IF NOT EXISTS last_charge DATETIME DEFAULT null;
ALTER TABLE users ADD COLUMN IF NOT EXISTS balance DECIMAL(19, 4) not null DEFAULT 0.0000;
